# Project: Stack_MIPT
# Makefile created by Red Panda C++ 3.4.3279

CXX      = "g++.exe"
CC       = "g++.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-fno-ms-extensions" "-pipe" "-Wall" "-Werror=return-type" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-fno-ms-extensions" "-pipe" "-Wall" "-Werror=implicit-int" "-Werror=return-type" "-D_DEBUG"
NASM_FLAGS   =  "-f" "elf64" "-g"
WINDRESFLAGS = 
RES      = Stack_MIPT_private.res
OBJ      = macroces.o stack_constructor.o main.o $(RES)
BIN      = Stack_MIPT.exe
LINKOBJ  = "macroces.o" "stack_constructor.o" "main.o" "Stack_MIPT_private.res"
CLEANOBJ = "macroces.o" "stack_constructor.o" "main.o" "Stack_MIPT_private.res" "Stack_MIPT.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

Stack_MIPT.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "Stack_MIPT.exe" $(LIBS)

macroces.o: macroces.cpp stack_constructor.h
	$(CXX) -c "macroces.cpp" -o "macroces.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=windows-1251

stack_constructor.o: stack_constructor.cpp stack_constructor.h
	$(CXX) -c "stack_constructor.cpp" -o "stack_constructor.o" $(CXXFLAGS) 

main.o: main.cpp stack_constructor.h
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS) 

Stack_MIPT_private.res: Stack_MIPT_private.rc 
	$(WINDRES) -i "Stack_MIPT_private.rc" --input-format=rc -o "Stack_MIPT_private.res" -O coff $(WINDRESFLAGS) 

